server:
  port: 8011
spring:
  application:
    name: fmea
#配置数据源
  datasource:
    url: jdbc:sqlite:C:\\sqlite\\fmea.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500
        # 连接池中的最大空闲连接
        min-idle: 0
        # 连接池中的最小空闲连接
    lettuce:
      shutdown-timeout: 0
      # 连接超时时间（毫秒）
#配置mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.rb.fmea.entities
#日志位置
logging:
  path: C:/log


